name: CI
on:
  pull_request:
    paths:
      - 'deepchecks/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
#        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - name: Install OS Dependencies
        if: matrix.os == 'macos-latest'
        run: brew install libomp
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - run: poetry install
      - run: poetry run pytest
    continue-on-error: true
  test-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: poetry install --only main
      - run: poetry run python -m unittest test_imports.py
